<?php

/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/2
 * Time: 15:49
 */
class MyAccessFilters extends \yii\base\ActionFilter
{
    public function beforeAction($action){
        if(!\Yii::$app->user->can($action->uniqueId)){
            //提示403
            throw new HttpException(403,'对不起,您没有改操作权限!');
            return false;

        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}